### ISSUE TITLE
html注释转换的问题

### ISSUE THREAD

**Issue by vinurs** [cassc/hiccupandhtml#1]
无论在http://html2hiccup.buttercloud.com/ 还是在你的最新的转换里面，对于html注释部分好像都是直接转成字符串的，这个是否可以转成clojure的注释风格？

**Comment by cassc** [comment]
HTML注释其实不是元素，在Hiccup没有适当表示方法，才显示为字符串，可以参考[来源](
https://github.com/davidsantiago/hickory/blob/master/src/cljs/hickory/core.cljs#L74)

暂时把`<!-- xxx -->`转换为Hiccup`(comment "xxx")`的形式，你可以测试下。

**Comment by vinurs** [comment]
测试了一下，可以了，谢谢
